openapi: '3.0.2'
info:
  title: Linguakit
  version: '2.0'
servers:
  - url: http://0.0.0.0:3000/v2.0
paths:
  /:
    get:
      description: "Blank endpoint for testing"
      responses:
        '200':
          description: Test endpoint
  /dep:
    post:
      summary: "DepPattern: grammar parser"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              allOf:
                - $ref: '#/components/schemas/normaldata'
                - $ref: '#/components/schemas/outputdep'  
      responses:
        '200':
          description: OK
        '500':
          description: Error in Linguakit API code, check log
  /tagger:
    post:
      summary: "Tagger: postagger"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/normaldata'
      responses:
        '200':
          description: OK
        '500':
          description: Error in Linguakit API code, check log
  /rel:
    post:
      summary: "Triples extractor"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/normaldata'
      responses:
        '200':
          description: OK
        '500':
          description: Error in Linguakit API code, check log



components:
  schemas:
    normaldata:      # Object definition
      type: object
      properties:
        lang:
          description: "Language can be: en, es, pt, gl"
          type: string
          enum: [en, es, pt, gl]
        text:
          description: "Text to be analyzed"
          format: textarea
          type: string
          minLength: 10
      required:
        - lang
        - text

    outputdep:
      type: object
      properties:
        output:          
          description: "Type of output. Options: conll (CoNLL), c (Tagged text with syntactic information (for correction rules), fa (Full dependency analysis), a (Simple dependency analysis)"
          type: string
          enum: [conll, c, fa, a]